### ISSUE TITLE
Add a way to refresh the page so requests can be updated without closing the app

### ISSUE THREAD

**Issue by kpachhai** [tuum-tech/vouch-capsule#28]
Currently, the requests are never updated while you're on the app. You close and re-open or only by relogging triggers the REST API call to fetch the latest status on the past requests. This behavior should be changed so when you pull the screen down, the screen should automatically trigger a refresh.

**Comment by wakqasahmed** [comment]
1) Is this for `Request` page OR also for `Home` page?
2) What are the cases it will be effective for? because the validation will take a few days and will not be right away. So the applications I see are
* user submits another validation request, meanwhile a previous one got validated so to update its status "scroll refresh" helps
* user submits a validation request and keeps the application open (for 3 days), he refreshes the page and since by that time the request was approved the latest status is fetched

Is that what we are aiming for?

**Comment by kpachhai** [comment]
1) Both
2) all cases. It's just a nice to have feature because people may not wanna quit the app and reopen just to see the updated status on their requests. Also, this is great for UX
